
packages:
  all:
    target: [broadwell]
    variants: build_type=Release cxxstd=17
    buildable: true
    version: []
    providers:
      gl: [mesa18]
      glu: [mesa18]
    compiler: []
  mesa18:
    variants: ~llvm+glx+opengl swr=none
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  mesa:
    variants: ~llvm+glx+opengl swr=none
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  geant4:
    variants: ~qt~opengl+vecgeom cxxstd=17
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  boost:
    variants: +python
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  xercesc:
    variants: cxxstd=11
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  root:
    version: [6.22.06]
    variants: +davix+gsl+asimage+math~memstat+minuit+mlp~mysql+opengl~postgres~pythia6+pythia8+python~qt4+r+root7+roofit+rpath~shadow+sqlite+ssl~table+tbb+threads+tmva+unuran+vc+vdt+vmc+x+xml+xrootd cxxstd=17
    buildable: true
    target: []
    providers: {}
    compiler: []
  marlin:
    variants: ~lccd
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  ocaml:
    version: [4.10.0]
    variants: ~force-safe-string
    buildable: true
    target: []
    providers: {}
    compiler: []
  pythia8:
    version: [8303]
    buildable: true
    target: []
    providers: {}
    compiler: []
  gaudi:
    version: [35.0]
    buildable: true
    target: []
    providers: {}
    compiler: []
  curl:
    version: [7.72.0]
    buildable: true
    target: []
    providers: {}
    compiler: []
  python:
    version: [3.7.8]
    buildable: true
    target: []
    providers: {}
    compiler: []
  delphes:
    version: [3.4.3pre06]
    buildable: true
    target: []
    providers: {}
    compiler: []
  py-numpy:
    version: [1.18.5]
    buildable: true
    target: []
    providers: {}
    compiler: []
  py-tensorflow:
    variants: [~cuda~nccl]
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  fmt:
    version: [6.1.2]
    buildable: true
    target: []
    providers: {}
    compiler: []
  expat:
    version: [2.2.9]
    buildable: true
    target: []
    providers: {}
    compiler: []
  perl:
    version: [5.30.3]
    buildable: true
    target: []
    providers: {}
    compiler: []
  whizard:
    variants: ~fastjet~latex+lcio~lhapdf+openloops~openmp+pythia8 hepmc=2
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  k4fwcore:
    version: [1.0pre05]
    buildable: true
    target: []
    providers: {}
    compiler: []
  cmake:
    version: [3.18.4]
    buildable: true
    target: []
    providers: {}
    compiler: []
  assimp:
    buildable: true
    version: [master]
    target: []
    providers: {}
    compiler: []
  dd4hep:
    variants: +assimp+lcio+xercesc+hepmc3+geant4+edm4hep
    buildable: true
    version: []
    target: []
    providers: {}
    compiler: []
  g4photonevaporation:
    externals:
    - spec: "g4photonevaporation@5.7"
      prefix: /cvmfs/sw.hsf.org/share/data/g4photonevaporation-5.7-vontejgdceozwf5ymnc6wyarevch72kg
    - spec: "g4photonevaporation@5.5"
      prefix: /cvmfs/sw.hsf.org/share/data/g4photonevaporation-5.5-ytgakfl5dk6wqull7dtaebfyyb5tkg7v
    buildable: False
  g4emlow:
    externals:
    - spec: "g4emlow@7.13"
      prefix: /cvmfs/sw.hsf.org/share/data/g4emlow-7.13-r5b7ydx472oljpocyxiruqqnie2tkc3d
    - spec: "g4emlow@7.9.1"
      prefix: /cvmfs/sw.hsf.org/share/data/g4emlow-7.9.1-u3eog3pkan5mjap2hdj65no4yiiegrr4
    buildable: False
  g4abla:
    externals:
    - spec: "g4abla@3.1"
      prefix: /cvmfs/sw.hsf.org/share/data/g4abla-3.1-2jxylbld7geymksmd4lgddttt3sq5jdg
    buildable: False
  g4ensdfstate:
    externals:
    - spec: "g4ensdfstate@2.3"
      prefix: /cvmfs/sw.hsf.org/share/data/g4ensdfstate-2.3-jrydtxs2klc2zkqwdwslurjjmfbuh7nz
    - spec: "g4ensdfstate@2.2"
      prefix: /cvmfs/sw.hsf.org/share/data/g4ensdfstate-2.2-u3ihhqb7buve6cpfjjsexds6hucxpewp
    buildable: False
  g4incl:
    externals:
    - spec: "g4incl@1.0"
      prefix: /cvmfs/sw.hsf.org/share/data/g4incl-1.0-qsbncfghs3lzujqpewl7k6mibob4v5qh
    buildable: False
  g4ndl:
    externals:
    - spec: "g4ndl@4.6"
      prefix: /cvmfs/sw.hsf.org/share/data/g4ndl-4.6-zlys4znfgnnxr7fqrct2afjshxxsgfdw
    buildable: False
  g4particlexs:
    externals:
    - spec: "g4particlexs@3.1"
      prefix: /cvmfs/sw.hsf.org/share/data/g4particlexs-3.1-sj23ktyy4n62tyo2vf2igm2avkblu65f
    - spec: "g4particlexs@2.1"
      prefix: /cvmfs/sw.hsf.org/share/data/g4particlexs-2.1-blzstre64pp64czkdvkfdmfoajtf3rdz
    buildable: False
  g4pii:
    externals:
    - spec: "g4pii@1.3"
      prefix: /cvmfs/sw.hsf.org/share/data/g4pii-1.3-zp2rq2nom6bevtohjiftfuhc27n7xd55
    buildable: False
  g4radioactivedecay:
    externals:
    - spec: "g4radioactivedecay@5.6"
      prefix: /cvmfs/sw.hsf.org/share/data/g4radioactivedecay-5.6-wyhngfhkfpwxbeo4udz7zpiyr5rw3bbb
    - spec: "g4radioactivedecay@5.4"
      prefix: /cvmfs/sw.hsf.org/share/data/g4radioactivedecay-5.4-oolrwvpyxrywewesowrodnsmef2azn6h
    buildable: False
  g4realsurface:
    externals:
    - spec: "g4realsurface@2.2"
      prefix: /cvmfs/sw.hsf.org/share/data/g4realsurface-2.2-t2np7vfwhwc5k7szhfdkjeitvazji4e4
    - spec: "g4realsurface@2.1.1"
      prefix: /cvmfs/sw.hsf.org/share/data/g4realsurface-2.1.1-5tbzwejlo4ax6ai27hznjgvu6r5lrloc
    buildable: False
  g4saiddata:
    externals:
    - spec: "g4saiddata@2.0"
      prefix: /cvmfs/sw.hsf.org/share/data/g4saiddata-2.0-77yzjy4zeieavelx3vnef3ztm6uxyu2f
    buildable: False
